<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Datasource\Exception\InvalidPrimaryKeyException;
use Cake\Datasource\Exception\RecordNotFoundException;
use Cake\Event\EventInterface;

/**
 * Subcategories Controller
 *
 * @property \App\Model\Table\SubcategoriesTable $Subcategories
 */
class SubcategoriesController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Authentication->addUnauthenticatedActions(['login']);

        $user = $this->Authentication->getIdentity();
        if (isset($user) and $user->role === 'user') {
            if (!in_array($this->request->getParam('action'), ['index', 'edit'])) {
                //$this->redirect($this->request->referer());
                $this->Flash->error('Usted no esta autorizado para acceder al Sitio Solicitado');
                $this->redirect(['controller' => 'Index', 'action' => 'index']);
            }
        }
        $this->loadCartProduct();
    }

    public function index()
    {
        $sub_categories = $this->Subcategories->find('all', [
            'contain' => ['Categories'],
        ]);
        //debug($sub_categories->toArray());
        $this->set(compact('sub_categories'));
    }

    public function add()
    {
        $sub_categories = $this->Subcategories->newEmptyEntity();

        $model_categories = $this->getTableLocator()->get('Categories');

        $categories = $model_categories->find(
            'list',
            [
            'keyField' => 'idcategories',
            'valueField' => 'name',
            'order' => ['name' => 'ASC'],
            ]
        )->toArray();

        if ($this->request->is('post')) {
            $sub_categories = $this->Subcategories->patchEntity($sub_categories, $this->request->getData());
            if ($this->Subcategories->save($sub_categories)) {
                $this->Flash->success(__('La Subcategoria se almaceno correctamente.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('La Subcategoria no se pudo guardar. Intente nuevamente.'));
        }

        $this->set(compact('categories'));
        $this->set(compact('sub_categories'));
    }

    public function edit($id = null)
    {
        try{

            $sub_categories =  $this->Subcategories->get($id);


            $model_categories = $this->getTableLocator()->get('Categories');

            $categories = $model_categories->find(
                'list',
                [
                    'keyField' => 'idcategories',
                    'valueField' => 'name',
                    'order' => ['name' => 'ASC'],
                ]
            )->toArray();
            $this->set(compact('categories'));

            if ($this->request->is(['patch', 'post', 'put'])) {
                $sub_categories = $this->Subcategories->patchEntity($sub_categories, $this->request->getData());
                if ($this->Subcategories->save($sub_categories)) {
                    $this->Flash->success(__('La Subcategoria se almaceno correctamente.'));

                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error(__('La Subcategoria no se pudo guardar. Intente nuevamente.'));

            }
            $this->set(compact('sub_categories'));
        } catch (InvalidPrimaryKeyException $e){
            $this->Flash->error(__('Error al almacenar los cambios. Intenta nuevamente'));

        } catch (RecordNotFoundException $e){
            $this->Flash->error(__('Error al almacenar los cambios. Intenta nuevamente'));
        }
        catch (Exception $e){
            $this->Flash->error(__('Error al almacenar los cambios. Intenta nuevamente'));
        }
    }

    public function getSubCategoriesByCategoryList($category = null)
    {



        //comprobacion de definicion de variable
        if ($category != null) {

            $subcategories = $this->Subcategories->find(
                'list',
                [
                    'keyField' => 'idsubcategories',
                    'valueField' => 'name',
                    'order' => ['name' => 'ASC'],
                ]
            )
                ->where(['categories_idcategories' => $category])
                ->toArray();

            return $subcategories;
        }

        return false;
    }

    public function getSubCategoriesByCategory($category = null)
    {

        //comprobacion de definicion de variable
        if ($category != null) {

            $subcategories = $this->Subcategories->find(
                'list',
                [
                    'keyField' => 'idsubcategories',
                    'valueField' => 'name',
                    'order' => ['name' => 'ASC'],
                ]
            )
                ->where(['categories_idcategories' => $category])
                ->toArray();

            return $this->json($subcategories);
        }

        return $this->json(['result' => false]);
    }
}
